#配置调用product-service服务采用的负载均衡策略
PRODUCT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 2 # 切换实例的重试次数

#对请求和响应进行GZip压缩
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true

#暴露所有的健康监控节点
management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #默认的连接超时时间1秒,若1秒没有返回数据,自动的触发降级逻辑
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5 #触发熔断的最小请求次数，默认20
        errorThresholdPercentage: 10 #触发熔断的失败请求最小占比，默认50%
        sleepWindowInMilliseconds: 5000 #熔断多少秒后去尝试请求，默认是5S
spring:
  rabbitmq:
    host: 106.12.102.143
    virtual-host: /cny
    username: cny
    password: cny
